#version: '3.8'

services:
  frontendreact:
    build:
      context: ./front-endLAST/www2/www/firstproject # Path to frontend directory
      dockerfile: Dockerfile  # Relative Path to frontend Dockerfile
    ports:
      - "3000:80"  # Exposing React app on port 3000 "3000:3000"
    depends_on:
      - backendgo  # Ensure backend starts before frontend
    networks:
      - app-network

  backendgo:
    build:
      context: ./back-endLAST/DoneBE/TOOLS3BE # Path to  backend directory
      dockerfile: Dockerfile # Relative Path to Golang backend Dockerfile
    ports:
      - "8080:8080"  # Exposing Golang backend on port 8080
    depends_on:
      - databasemongo  # Ensure database starts before backend
    environment:
      - DB_HOST=databasemongo
      - DB_PORT=27017  # MongoDB port 
      - DB_NAME=packageTrackingDB 
      ##
    volumes:
      - ./back-endLAST/DoneBE/TOOLS3BE/.env:/app/.env  
    networks:
      - app-network

  databasemongo:
    image: mongo:latest  # official MongoDB image
    ports:
      - "27017:27017"  # Exposing MongoDB on port 27017
    volumes:
      - db_data:/data/db  # Persist MongoDB data across container restarts
    environment:
      - MONGO_INITDB_DATABASE=packageTrackingDB  # Database name
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: # Named volume to persist MongoDB data
    name: la_db_data